dependencies:
- alias: activiti-cloud
  name: activiti-cloud-full-example
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.3.0
- name: activiti-cloud-connector-helloworld
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- name: jx-spring
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.9
